[package]
name = "self-update-tester"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
eyre = "0.6.12"
inquire = "0.7.5"
rand = "0.9.0"
self_update = "0.42.0"
